config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :islands do
    resources :bookings, except: :index
  end
  resources :bookings, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/island.rb
class Island < ApplicationRecord
  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_name?
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :islands, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:new, :show, :create]

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.create(booking_params)
    @booking.island = @island
    @booking.user = current_user
    if @booking.save
      redirect_to island_booking_path(@island, @booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def set_booking
    @island = Island.find(params[:island_id])
  end

  def booking_params
    params.require(:booking).permit(:island_id, :start_date, :end_date)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  def index
    @islands = Island.all
    @markers = @islands.geocoded.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude,
        info_window: render_to_string(partial: "info_window", locals: { island: island }),
        image_url: helpers.asset_url("marker.png")
      }
    end
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @islands = Island.where(sql_query, query: "%#{params[:query]}%")
    else
      @islands = Island.all
    end
  end

  def new
    @island = Island.new
  end

  def create
    @user = current_user
    @island = Island.new(island_params)
    @island.user = @user
    if @island.save
      redirect_to islands_path
    else
      render :new
    end
  end

  def show
    @island = Island.find(params[:id])
  end

  def edit
    @island = Island.find(params[:id])
  end

  def update
    @island = Island.find(params[:id])
    @island.update(island_params)
    redirect_to island_path(@island)
  end

  def destroy
    @island = Island.find(params[:id])
    @island.destroy
    redirect_to islands_path
  end

  private

  def island_params
    params.require(:island).permit(:name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-4">
  <h1> All Bookings </h1>

  <% @bookings.each do |booking| %>
  <div class="container mt-4 pl-0 pr-0">
    <div class="card-all-bookings">
      <%= cl_image_tag booking.island.photo.key, height: 300, crop: :fill %>
      <div class="card-all-bookings-details">
        <h2><%= booking.island.name%></h2>
        <p><span>Check in: </span> <%= booking.start_date %></p>
        <p><span>Check out: </span> <%= booking.end_date %></p>
        <p><span>Booked for: </span><%= ((booking.end_date - booking.start_date).to_i)%> days<p>
        <p><span>Total price: </span>$ <%= ((booking.end_date - booking.start_date).to_i)*booking.island.price %><p>
      </div>
    </div>
    </div>
  <%end%>
  <div class="mt-4">
  <%= link_to "Back", islands_path, class: 'btn btn-primary btn-lg btn-custom' %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class='container py-5 '>
 <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-sm-6">
      <p> <%= current_user.name %></p>
      <%= simple_form_for [@island, @booking] do |f| %>
       <h1 class="mb-4">Book <%= @island.name %> Island</h1>
        <div class="card py-3 bg-color grey rounded-10">
        <div class="card-body">
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.submit 'Book', class: "btn btn-default btn-primary btn-md m-1" %>
          <%= link_to "Cancel", islands_path, class: 'btn btn-primary btn-md' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-4">
<h3><b><%= @island.name %></b></h3>

<div class="card-product">
  <%= cl_image_tag @booking.island.photo.key, crop: :fill %>
    <div class="card-product-infos">
        <p><strong>Price per day: </strong> $<%= @island.price %></p>
        <p><strong>Check in: </strong> <%= @booking.start_date.to_s %></p>
        <p><strong>Check out: </strong> <%= @booking.end_date.to_s %></p>
        <p><strong>Total: </strong> $<%= ((@booking.end_date - @booking.start_date).to_i)*@island.price %></p>
        <p><strong>Island description: </strong><%= @island.description %></p>
    </div>
</div>

<div class="d-flex mt-4">
  <%= link_to "Back", islands_path, class: 'btn btn-primary mr-2' %>
  <%= link_to "All your bookings", bookings_path, class: 'btn btn-primary' %>
</div>
</div>

app/views/islands/_form.html.erb
<%= simple_form_for (@island) do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text%>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-outline-primary'%>
  <%= link_to 'Cancel', islands_path, class: 'btn btn-danger'%>
<% end %>

app/views/islands/_info_window.html.erb
<div class="card">
  <img src="<%= cl_image_path island.photo.key, height: 300, crop: :fill %>" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"> <%= island.name %> </h5>
    <p class="card-text"> $ <%= island.price %> / Day</p>
  </div>
</div>

app/views/islands/edit.html.erb
<div class="container py-5">
  <h1 class="text-center mb-4">Edit Island Info</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-sm-6">
      <%= render "form", island: @island %>
    </div>
  </div>
</div>

app/views/islands/index.html.erb
<div class="container py-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1>Our beautiful islands</h1>
      
      <div class="mr-2 d-flex align-items-center">
        <%= form_tag islands_path, class:"d-flex justify-content-between mr-2", method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find an island"
          %>
          <%= submit_tag "Search", class: "btn btn-primary ml-1 mr-2" %>
        <% end %>

        <% if current_user.owner == true %>
          <%= link_to "Create new Island", new_island_path, class: 'btn btn-blue ' %>
        <% end %>
      </div>
  </div>

  <%# ---------------- Main container start ---------------- %>
  <div class="main-container d-flex ">
    
    <%# ---------------- All islands cards start ---------------- %>
    <div class="row flex-grow-1 mr-2 cards-max">
      <% @islands.each do |island| %>
        <div class="col-12 col-lg-6 col-md-6 mb-4">
          <%= link_to island_path(island), class: 'text-decoration-none' do %>
            <% if island.photo.attached? %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path island.photo.key, height: 300, crop: :fill %>')">
                  <%= island.name %>
                </div>
                
                <% else %>

                <div class="card-category" style="background-image: linear-gradient(rgba(20,20,20,0.3))">
                  <%= island.name%>
                </div>
                
              <% end %>
            <% end %>
        </div>
      <% end %>
    </div>
    <%# ---------------- All islands cards end ---------------- %>
    
    <%# ---------------- Mapbox start ---------------- %>
    <div id="map"
     class="position-sticky"
     style="width: 400px; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <%# ---------------- Mapbox start ---------------- %>

  </div>
  <%# ---------------- Main container end ---------------- %>


</div>

app/views/islands/new.html.erb
<div class="container py-5">
  <h1 class="text-center mb-4">Add an Island</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-sm-6">
      <%= render "form", island: @island %>
    </div>
  </div>
</div>

app/views/islands/show.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-sm-6 col-lg-6">

    <div class="d-flex justify-content-between align-items-center mb-4">

      <h1 class=""> <%= @island.name %> </h1>

      <div class='d-flex align-items-center '>
        <% if current_user.owner == true %>
          <%= link_to "Edit Island", edit_island_path, class: 'btn btn-blue btn-sm mr-2' %>
          <%= link_to "Delete Island", island_path(@island), 
            method: :delete, data: { confirm: 'Are you sure?' }, 
            class: 'btn btn-blue btn-sm' %>
        <% end %>
      </div>

    </div>


        <div class="card-trip">
          <%= cl_image_tag @island.photo.key, height: 300, crop: :fill %>
            <div class="card-trip-infos">
              <div>
                <h2> <%= @island.name %></h2>
                <p> <%= @island.description %></p>
              </div>
          <h2 class="card-trip-pricing"> $<%= @island.price %> </h2>
          <%= image_tag "user.svg", class:"card-trip-user avatar-bordered bg-color" %>
          </div>
            <div class="book d-flex">
                <%= link_to "Book Now",  new_island_booking_path(@island), class: 'btn btn-cta2 text-white btn-md w-100 mr-2' %>
                <%= link_to "Cancel",  islands_path, class: 'btn btn-outline-danger btn-md w-100' %>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAnIsland</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/1532435/pexels-photo-1532435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">

  <div class="container">
    <h1>ISLANDS FOR RENT</h1>
    <p>Find a private island to rent now! Exclusive islands for honeymoons, diving, fishing, family and weddings.</p>
    <%= link_to "Discover Now", islands_path, class: "btn btn-cta btn-lg text-white" %>
  </div>
</div>

<div class="container">
    <h1 class="content mb-4">About Us</h1>
    <div class="row">
        <div class="col-md-12 d-flex">
            <%= cl_image_tag("lkpxdqjmjysmb5pvarly",
               width: 500, height: 300, crop: :fill) %>
            <div class ="content p-5">
             <p>We’re excited to welcome you to our beautiful islands!
              Come and relax on our stunning beaches and feel the freedom to explore.</p>
            <p>“Nights and days came and passed and summer and winter and the rain. And it was good to be a little Island.
                A part of the world and a world of its own. All surrounded by the bright blue sea.”
                ― Margaret Wise Brown, The Little Island</p>
            </div>
        </div>
      </div>
    </div>

    <section class="home-testimonial">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center testimonial-pos">

                <div class="col-md-12 pt-4 d-flex justify-content-center">
                    <h3>Testimonials</h3>
                </div>

                <div class="col-md-12 d-flex justify-content-center">
                    <h2>Visitors experience</h2>
                </div>

            </div>
            <section class="home-testimonial-bottom">
                <div class="container testimonial-inner">
                    <div class="row d-flex justify-content-center">

                        <div class="col-md-4 style-3">
                            <div class="tour-item ">
                                <div class="tour-desc bg-white">
                                    <div class="tour-text color-grey-3 text-center">“Great experience! I use this app since a few years to book every family vacation. The islands listed here have great service and high standards.”</div>
                                    <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://avatars.githubusercontent.com/u/85581357?v=4" alt=""></div>
                                    <div class="link-name d-flex justify-content-center">Bhavna</div>
                                    <div class="link-position d-flex justify-content-center">Manager</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 style-3">
                            <div class="tour-item ">
                                <div class="tour-desc bg-white">
                                        <div class="tour-text color-grey-3 text-center">“Went for a weekend trip to Palawan. That was a last minute booking. For any last minute trip, I highly recommend Rent An Island (and Palawan too!...) ”</div>
                                        <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://avatars.githubusercontent.com/u/85569294?v=4" alt=""></div>
                                        <div class="link-name d-flex justify-content-center">Julie</div>
                                        <div class="link-position d-flex justify-content-center">CEO</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 style-3">
                            <div class="tour-item ">
                                <div class="tour-desc bg-white">
                                    <div class="tour-text color-grey-3 text-center">“I've been to Lifou and Bora Bora with friends. The service at both places is excellent. Rent An Island proposes the best private islands.”</div>
                                    <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://avatars.githubusercontent.com/u/79565709?v=4" alt=""></div>
                                    <div class="link-name d-flex justify-content-center">Christian</div>
                                    <div class="link-position d-flex justify-content-center">Businessman</div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
        </div>
    </section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © 2021 Rent an island | Les Kokottes, Moka, Mauritius
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "island-logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All Islands", islands_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.svg", class: "avatar dropdown-toggle change-color", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.owner == true %>
              <%= link_to "Add an Island", new_island_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Our islands", islands_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>